apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-api-prefix
spec:
  stripPrefix:
    prefixes:
      - /api
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: petclinic
  labels:
    labels:
      traefik.http.middlewares.test-stripprefix.stripprefix.prefixes: /owner,/owner/api
spec:
  entryPoints:
    - web
    - websecure
  routes:
    # ----------------------------------------------------------------------------------------------------
    # Routes everything starting with /v1.0 to the DAPR sidecar
    # ----------------------------------------------------------------------------------------------------
    - kind: Rule
      match: Host(`owner.petclinic.127.0.0.1.nip.io`) && PathPrefix(`/v1.0`)
      priority: 20
      services:
        - name: petclinic-owner-api-dapr
          port: dapr-http
    # ----------------------------------------------------------------------------------------------------
    # Catch-all rule that routes any unknown subpath to the UI. This has to be the lowest priority of all.
    # ----------------------------------------------------------------------------------------------------
    - kind: Rule
      match: Host(`owner.petclinic.127.0.0.1.nip.io`)
      priority: 10
      services:
        - name: petclinic-owner-ui
          port: http          