apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: petclinic
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`petclinic.127.0.0.1.nip.io`) && Path(`/petclinic/api`)
      priority: 10
      services:
        - name: petclinic-owner-api-dapr
          port: dapr-http