---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: owner
spec:
  selector:
    matchLabels:
      app: owner
  template:
    metadata:
      labels:
        app: owner
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: owner
        dapr.io/app-port: "3000"
        dapr.io/log-level: debug
        dapr.io/sidecar-listen-addresses: "[::],0.0.0.0"
        dapr.io/config: "tracing"

    spec:
      containers:
      - name: petclinic-owner
        image: spolab/petclinic-owner:v0.0.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: STATESTORE_NAME
            value: owner-state
          - name: PUBSUB_NAME
            value: owner-pubsub
          - name: PUBSUB_TOPIC
            value: owner
        ports:
        - name: rest
          containerPort: 3000
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: owner-pubsub
spec:
  type: pubsub.in-memory
  version: v1
  metadata: []
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: owner-state
spec:
  type: state.in-memory
  version: v1
  metadata:
    - name: actorStateStore
      value: true
---
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: owner-subscription
spec:
  topic: owner
  route: /registered
  pubsubname: owner-pubsub
scopes:
  - owner