# Copyright 2022 Alessandro Santini
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# 	http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
name: Build the DAPR Pet Clinic

env:
  VET_ACTOR_IMAGE: ghcr.io/spolab/petclinic-vet-actor:latest
  VET_API_IMAGE: ghcr.io/spolab/petclinic-vet-api:latest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/spolab/golang-builder:v0.0.1
    steps:
    - name: Login to GHCR repository
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: spolab
        password: ${{ secrets.GHCR_PAT }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Perform code vetting
      run: go vet ./...
    - name: Perform code testing
      run: go test ./...
    - name: Compile Vet Actor
      run: go build -o bin/vet/actor cmd/vet/actor/main.go
    - name: Build Vet Actor image
      run: docker build --file docker/Dockerfile --build-arg APP=bin/vet/actor --build-arg DESC="dapr petstore vet actor" --tag $VET_ACTOR_IMAGE .
    - name: Push Vet Actor image
      run: docker push $VET_ACTOR_IMAGE
    - name: Compile Vet API
      run: go build -o bin/vet/api cmd/vet/api/main.go
    - name: Build Vet API image
      run: docker build --file docker/Dockerfile --build-arg APP=bin/vet/api --build-arg DESC="dapr petstore vet api" --tag $VET_API_IMAGE .
    - name: Push Vet API image
      run: docker push $VET_API_IMAGE
